### ISSUE TITLE
Practica 5

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-dream-team1#1]
[SonarcloudG.pdf](https://github.com/SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-dream-team1/files/9702868/SonarcloudG.pdf)

**Comment by salathiel1999** [comment]
[Practica Calidad Metricas.pdf](https://github.com/SistemasTecTlaxiaco/practica-5-practica-de-calidad-metricas-dream-team1/files/9672252/Practica.Calidad.Metricas.pdf)

**Comment by salathiel1999** [comment]
> Uploading Practica Calidad Metricas.pdf…

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by josealfredo79** [comment]
Calificacion 19
